name: virtam
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  input_quantity: ^2.2.0
  intl: ^0.19.0
  provider: ^6.1.1
  cloud_firestore: ^4.15.5
  firebase_core: ^2.30.1
  checkbox_grouped: ^2.0.0
  beamer: ^1.6.0
  pedometer: ^4.0.1
  percent_indicator: ^4.2.3
  permission_handler: ^11.3.0
  flutter_local_notifications: ^16.3.2
  timezone: ^0.9.2
  rxdart: ^0.27.7
  flutter_timezone: ^1.0.8
  awesome_notifications: ^0.9.2
  #android_alarm_manager_plus: ^3.0.4
  phone_form_field: ^3.0.1
  intl_phone_number_input: ^0.7.4
  firebase_auth: ^4.17.6
  hive: ^2.2.3
  shared_preferences: ^2.2.2
  health: ^9.0.1
  device_info_plus: ^9.1.2
  #daily_pedometer: ^0.0.5
  #flutter_background_service: ^5.0.5
  #flutter_background_service_android: ^6.2.2
  #animated_weight_picker: ^1.0.3
  location: ^5.0.3
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  #sensors: ^2.0.3
  flutter_staggered_grid_view: ^0.7.0
  syncfusion_flutter_charts: ^25.1.35
  banner_carousel: ^1.2.1
  firebase_storage: ^11.6.9
  image_picker: ^1.0.7
  flutter_lints: ^3.0.1

  flutter_localizations:
    sdk: flutter
  logger_util: ^0.0.1
  logger: ^2.2.0
  background_fetch: ^1.3.2
  firebase_messaging: ^14.9.1
  overlay_support: ^2.1.0
  onesignal_flutter: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
    intl: ^0.18.1





flutter:

  fonts:
    - family: Almarai
      fonts:
        - asset: fonts/Almarai-Bold.ttf
          weight: 700
        - asset: fonts/Almarai-Regular.ttf

  uses-material-design: true
  assets:
    - images/
    - images/splashScreenImages/

flutter_intl:
  enabled: true